# Generated by Django 6.0.5 on 2026-05-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='number_of_seats',
            field=models.PositiveBigIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
