# Generated by Django 6.0.5 on 2026-05-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='desitination',
            new_name='destination',
        ),
    ]
